version: '3.7'

services:
  pgsql:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: pgsql
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d/:ro
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: pgdatabase
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pguser" ]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'

volumes:
  pg-data:
    driver: local